name: smart_ix_takehome
description: Smart IX Flutter Technical Test.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
 # For functional programming 
  dartz: ^0.10.1
  # For value equality
  equatable: ^2.0.3

  flutter:
    sdk: flutter
  # for state-managements
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.5+1
  # for app localization
  flutter_localizations:
    sdk: flutter
  # for responsive design
  flutter_screenutil: ^5.5.3+2
  # for dependency injection
  flutter_svg: ^1.1.1+1
  get_it: ^7.2.0
  # for formatting data like date
  intl: ^0.17.0
  # for logging 
  logger: ^1.1.0
  # for local storage
  shared_preferences: ^2.0.15

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
